### ISSUE TITLE
Links in extra segment / webpage are outdated

### ISSUE THREAD

**Issue by mywave82** [adplug/adplug#107]
http://adplug.github.io/extras.html

Some of the music I have been able to source. Please see here: https://stian.cubic.org/music.php

**Comment by Malvineous** [comment]
You can probably contact the Super Fighter team and they will reupload the missing songs you have found (contact link at https://www.superfighter.com/index.html), they are pretty responsive.

If the page needs to be changed you can submit a PR on the web page repo with your changes: https://github.com/adplug/adplug.github.io/blob/master/extras.html
