### ISSUE TITLE
Multiple additional errors, mostly OOB reads, found by AFL++

### ISSUE THREAD

**Issue by debrouxl** [adplug/adplug#110]
Thanks for integrating Alex Miller's fixes :)
I rebuilt adplug (then at commit 480ed3c9fae57d732b7c12e0afcfd02e3cf4ee88 ) with them and AddressSanitizer instrumentation by AFL++'s afl-clang-fast(++), and restarted fuzzing with AFL++'s afl-fuzz, using the test suite as initial corpus (minus the ref files, but including the .cpp files I didn't notice at first...).
The first crashes (memory errors turned into aborts, segmentation faults, etc.) were found quickly, and a bit over a core-day later, the set of samples which crash asan-instrumented adplug has grown to something I can post. At the time of this writing, afl-fuzz has examined only about a third of the nearly 2000 paths it found, so there's a lot of room for finding more paths and issues.

I ran over half of the samples manually, all of them reproduced. The output shows multiple OOB reads of various sizes, at least one overlapping memcpy, at least one wild read.

[adplug_asan_crashes_20200512_1.tar.gz](https://github.com/adplug/adplug/files/4613620/adplug_asan_crashes_20200512_1.tar.gz)

**Comment by Malvineous** [comment]
@miller-alex Help! :)

**Comment by miller-alex** [comment]
That doesn't surprise me at all. There are a lot of players I haven't looked at yet, but a quick glimpse showed their code quality isn't much better. I had planned to look at the remaining players anyway, but have been busy with other things in the last weeks.
I'll have a look when I have time, but I don't promise anything. And I don't mind if somebody else beats me :)

**Comment by miller-alex** [comment]
@debrouxl I've just added your samples to the tests locally, but I don't see any errors for the following two files, they just refuse to load:
* output/1/crashes/id:000047,sig:06,src:000857,time:11719025,op:havoc,rep:32
* output/2/crashes/id:000033,sig:06,src:001019,time:14254208+000728,op:splice,rep:128
This is probably due to different compiler/sanitizer options. Can you check these samples and post the output, so I can see what's going on?

**Comment by debrouxl** [comment]
My computer has now spent slightly over a core-month CPU time  executing the program 56+M times, finding 2300+ paths and 200 locally unique crashes which still yield "only" 19 unique SUMMARY lines
=> there's been no new crash since 12 days ago...
I guess I'll soon stop the fuzzing jobs and upload the latest set of crashing samples for coverage, but there shouldn't be anything more from that batch to fix.

**Comment by debrouxl** [comment]
Just uploading the final set of crashers produced in 1 core-month of Core i7-6700HQ. No new SUMMARY line.
[adplug_asan_crashes_20200527_1.tar.gz](https://github.com/adplug/adplug/files/4706237/adplug_asan_crashes_20200527_1.tar.gz)
