### ISSUE TITLE
certain IMF files can't be played

### ISSUE THREAD

**Issue by ghost** [adplug/adplug#115]
Hi

According to the developer of the Adplug plugin for foobar2000, there is a bug in the release version of Adplug which prevents loading some IMF files.

Please read here for all information (and the IMF files that don't load):

https://hydrogenaud.io/index.php?topic=119501.0

Here are the files: http://www.shikadi.net/wiki/files/keenmusic-r3.zip
(look inside "extracted IMFs" folder)

I post this message to ask if this bug is fixed already or still inside Adplug's code.

Thanks
Jessica

**Comment by jessicajonesunitedkingdom** [comment]
Thanks for the fix!
