### ISSUE TITLE
[Feature Request] Plugin for Audacious on Linux

### ISSUE THREAD

**Issue by starhawk64** [adplug/adplug#119]
Hello! I'm one of those insufferable dorks who uses Linux because blah blah blah [30min later] and besides, like I said, it "just works".

Sorry, my sarcasm level is over 9000 today, it helps me deal with a drenchingly rainy Thursday chasing a night of horrible sleep. I also have the sort of headache that feels like the asteroid from that stupid Bruce Willis movie missed its target and pinged off my braincase on its way to the next casting couch (sorry, that was awful)... and I have to buy groceries tomorrow with a nearly empty bank account.

I'm not trying to be rude, I'm trying to cope. Promise! :-|

Thing is, while I really like WinAMP's compact interface, it doesn't run on Linux, and my experience with WINE has been uhm frustrating, so I'm not really feeling encouragement in that direction... and given the current state of WinAMP dev work it uhm doesn't seem like there's any point in inquiring about a Linux port ;) Fortunately, smart idiots like me (lol) have a native Linux application that has a WinAMP Classic style interface, close enough to The Real Thing that it will even take in WinAMP *.wsz skins!

But it's not compatible otherwise with WinAMP, particularly in the plugin department. It's a distant descendant IIRC of Beep Media player and a thing called the Linux MultiMedia System (LMMS) that's so old the interface is a clay tablet and cuneiform stylus.

Meanwhile, I have some even more prehistoric files in *.lds form (aka the old Loudness Sound System stuff from when "PC" specifically meant something built like it came from a blacksmith's shop, but with IBM's logo on one side, and you interacted with it by typing cave paintings in at a C:\> prompt) and I've not listened to them since shortly before the extinction of the dinosaurs and I kind of miss that sound.

I suppose I'm a bit weird... does it show? ( :P )

Alas, no plugin is provided for Audacious, nor is one available -- at least to my knowledge -- that will play my prehistoric *.lds files. The one time I stuck my head into the "Support" forums for Audacious (quote marks very much deserved!) I was roundly informed, in the most horribly inconsiderate manner permissible, that such dusty old things were well beneath them and that I should get with the times and all that. When I tried to protest, I was sent packing before I could even politely ask them off my lawn.

Kids these days... hashtag-ess-emm-aitch. ( * :P intensifies* )

That was several years ago. I don't see the point in bothering them again...

...but if someone here would be kind enough to take pity on an old dorky Millenial such as myself (I'm a hardware guy, I can't code for cr*p... and before anyone asks, I'm 34 so yes I qualify as a Millennial, I'm just a bit of a curmudgeon these days), and toss me a version of AdPlug that knows how to talk to Audacious. I'd be greatly obliged.

Thanks in advance *tips fedora awkwardly*

**Comment by Malvineous** [comment]
What happened to the AdPlug plugin for Audacious?  I thought it had AdPlug support for a long time but they maintained their own plugin.

A lot of AdPlug development is done under Linux.  The Winamp plugin is about the only part that isn't.  I don't think anyone currently on the project has the time to start supporting new media players but we have no problem adopting the code if someone else is willing to write and maintain it.

I'd try to find out what happened to the old Audacious plugin and why you can't use it any longer.  I remember using Audacious when I first switched to Linux around 2003 and it worked with AdPlug back then, but I ended up moving to XMMS2 when I found Audacious would crash too regularly (something I'm sure has now been fixed.)  XMMS2 works really well but doesn't see much development these days and my AdPlug plugin for it is still unmerged after around 10 years so I'm now investigating what to jump ship to instead.  Looks like perhaps MPD might be the way to go as it seems to have a similar approach to XMMS2 but see much more active development.

**Comment by starhawk64** [comment]
Two immediate responses...

One, it's *phenomenally* stable now, I've been using it literally for like most of a decade and it's never ever ever crashed on me, even in Puppy which uhm had a habit of corrupting itself over time because the shutdown script doesn't 'umount' the root FS partition properly. (I left Puppy a very long time ago as well... almost exclusively for other reasons, although the corruption issues were a minor factor.)

Two... they *ever* had an AdPlug plugin? Nobody ever told me about that, nor did I know of it otherwise. I'm pretty sure the forum operated by carrier pigeon (lol) back when I was asking to try and make some antique LMMS or Beep plugin behave (and was shoved out quite rapidly for it!) but if anyone had mentioned an AdPlug plugin available at the time, I'd remember it -- and I don't. If it's of any significance... I'm on SolusOS 64bit right now. Probably will switch to Mint soon tho... Solus uses this very weird package type (and management system) called "eopkg" borrowed from some Turkish somethingorother distro that I've never heard of and while it's pretty and all I really miss *.deb packages and Ubuntu compatibility to the point that I may very well stay up half the night tonight *again* and either grab Ubuntu Budgie if it's still a thing, or Mint XFCE if not.

**Comment by Malvineous** [comment]
If I google for "audacious adplug" it takes me to [this page](https://audacious-media-player.org/news/43-audacious-3-10-released) which says back in a 2018 release they gave the AdPlug plugin a new settings window, so I guess they were maintaining it until at least back then?

**Comment by starhawk64** [comment]
That doesn't mean I knew about it ;) I'm not disputing its existence, just my awareness of said existence..

**Comment by starhawk64** [comment]
Were you able to contact the Audacious crew and find out anything?

For the record, I'm really not comfortable going back there after the way I was treated last time. That wasn't a cold shoulder, that was pitchforks and torches... bordering on "back the way you came, sonny!"

**Comment by Malvineous** [comment]
Do you have a link for that?  I'm surprised they were that harsh.

**Comment by starhawk64** [comment]
Sorry, I don't... honestly I'd be a bit surprised if they even still have it archived somewhere. I was in college when it happened, and I graduated mid-2009... I can't say, looking back, exactly when this was, but I really don't think it was close to graduation... early 2008 would be my best guess but I could easily be way off.

I have ADD (Attention Deficit Disorder) -- strangely, having music on as 'background noise' (just a phrase, music is wonderful!) really helps me focus. Alas, I also have a rather nasty case of thr memory issues that often tag along with ADD, and so pretty much everything from those years is a massive blur. It's a bit like the trick Lucas used in "Star Wars" (the first one, by way of release, back in, what, the mid 1970s?) to make the "hover effect" for Luke's landspeeder... long before they went and cleaned it up for the SE version ;)

Literally they smeared the film with Vaseline.

Yeah... whatever happened, although I don't remember *exactly* how it went down, it must've made quite an impression on me at the time! Otherwise I'd not remember it at all. (Before you ask, yes I'm quite sure of all that, no I couldn't possibly be getting it mixed up with other stuff, and no I'm not willing to question it further -- nor would I be at all comfortable trying again.)

**Comment by Malvineous** [comment]
You'll probably find most of the people involved back then have moved on now, and either way if you sign up without your real name nobody is going to know it's you anyway, so even if they are negative, you can easily walk away and forget about it.

Like I say I haven't used Audacious for over a decade so no idea where things are at now, so all I can suggest is using Google to see if you can find out whether it supports AdPlug now.  I would imagine it does, and there are no doubt instructions somewhere on how to set it up if it isn't enabled out of the box.

**Comment by starhawk64** [comment]
Ugh... :(

One apparently has to compile the "audacious-plugins" package specifically for AdPlug support. I'm on Linux Mint 20 right now, so that uses (in this case) Audacious 4.0.5... the corresponding audacious-plugins source package can be downloaded from a PPA that is found in any relevant Google search.

Unfortunately, I'm having a little trouble compiling it. Apparently this uses an 'autoconf' build system, so the command sequence is...
```
autoconf
./configure
make
make install
```

Great... except that autoconf chokes on some "M4" stuff. I can get past that by editing the 'configure.ac' file to include two additional lines...
```
m4_pattern_allow([^AC_])
m4_pattern_allow([^AM_])
```
...but when I run ./configure it still coughs up a lung and dies...
`$ ./configure
./configure: line 2274: AUD_COMMON_PROGS: command not found
./configure: line 2276: BUILDSYS_INIT: command not found
./configure: line 2277: BUILDSYS_SHARED_LIB: command not found
./configure: line 2279: syntax error near unexpected token `external'
./configure: line 2279: `AM_GNU_GETTEXT(external)'
$`

I don't know how to fix that :( suggestions?

**Comment by Malvineous** [comment]
Not really our area of expertise but usually with the autotools, only the package maintainer runs `autoconf` to produce the `configure` script, and end users such as yourself just run `./configure` as the first step.

Often git releases are missing the `configure` script though, so if you don't have it maybe you can find a release package somewhere that includes the script ready to go?

**Comment by starhawk64** [comment]
Nope, that's just how it comes :( I found a Mageia *.rpm with the adplug.so plugin lib in it, but it coughs up a lung and dies (some sort of absolutely inscrutable gobbledegook symbol error) when Audacious tries to load it...

...although...

That one was from Mageia-Tainted (i.e., the "some of this stuff isn't F|OSS" branch, meh) so I think I'll see if I can get the other one ("regular"/untainted Mageia) to work... there's one in each bin.

BTW, as an aside -- philosophically speaking... F|OSS is cool and I get it and why it is so, but I'm not out-and-out militant (i.e. "fundie" level fervent) about it... as in, I get that some people take the time to convert all their music to Ogg Vorbis or whatever and they absolutely refuse to use anything that isn't free... I don't have that much time and I don't think it's practical. I feel the same way about food... organic is great and all (I grew up on an organic small farm in the 1980s and early 1990s, true story) but if we're all eating hamburgers and you give me organic ketchup you're in for a bit of sharp wisecrackery and it will absolutely be at your expense.

Everything in moderation, including moderation itself. I use LibreOffice and won't touch MS Word but don't you dare take away my MP3s lol.

**Comment by starhawk64** [comment]
Here's the error I'm currently getting with that...

`$ audacious
ERROR plugin-load.cc:70 [plugin_load]: /usr/lib/x86_64-linux-gnu/audacious/Input/adplug.so could not be loaded: /usr/lib/x86_64-linux-gnu/audacious/Input/adplug.so: undefined symbol: _ZN15CAdPlugDatabase4loadENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
qt5ct: using qt5ct plugin
$ `

...about to go get that other version and stick it in there. We'll see :)

**Comment by starhawk64** [comment]
Er, yeah... same issue.

I kind of wonder if it's to do with how Mint calls its x64 platform "amd64" but Mageia calls it "x86_64".

...wait...

....OK yeah it's not a 32bit vs 64bit issue lol.

**Comment by Malvineous** [comment]
You definitely won't be able to take a compiled version for another system and have it work on your own, that'd be like having someone custom build a kitchen for your friend's house and then expecting it to fit perfectly in your own place.  Unless both your houses came off the same blueprints it ain't gonna happen.  But if the blueprints match (i.e. you are trying to run a version compiled for exactly the same distro and version that you are running yourself) then there will be no problem and everything will fit perfectly.  If there isn't a version for your distro then compiling it yourself will be the only option.

When you got errors about "some M4 stuff" and added the `m4_pattern_allow` lines, you told autoconf to pretend those missing commands existed and to keep going anyway.  This is like the post office telling you they can't send your parcel because you haven't paid enough postage, but you demand they take it anyway, then when the parcel gets returned you try to work out what is wrong with the address.  You will need to solve the initial problem (not enough postage / missing M4 macros) otherwise you'll end up focusing on trying to fix an unrelated error.

I would suggest you start by trying to compile Audacious itself first, as that is a known quantity and should work without having to change anything.  The process of doing that will ensure that most of what you need gets installed on your system.  Once that is working, then try the plugin, and hopefully it won't come up with quite so many complaints.

**Comment by mywave82** [comment]
On Sun, Sep 27, 2020 at 10:22 AM starhawk64 <notifications@github.com>
wrote:

> Ugh... :(
>
> One apparently has to compile the "audacious-plugins" package specifically
> for AdPlug support. I'm on Linux Mint 20 right now, so that uses (in this
> case) Audacious 4.0.5... the corresponding audacious-plugins source package
> can be downloaded from a PPA that is found in any relevant Google search.
>
> Unfortunately, I'm having a little trouble compiling it. Apparently this
> uses an 'autoconf' build system, so the command sequence is...
>
The sources you are testing here, are they available online somewhere. Can
you provide a working URL for their location

> autoconf
> ./configure
> make
> make install
>
> Great... except that autoconf chokes on some "M4" stuff. I can get past
> that by editing the 'configure.ac' file to include two additional lines...
>
> m4_pattern_allow([^AC_])
> m4_pattern_allow([^AM_])
>
> ...but when I run ./configure it still coughs up a lung and dies...
> $ ./configure ./configure: line 2274: AUD_COMMON_PROGS: command not found
> ./configure: line 2276: BUILDSYS_INIT: command not found ./configure: line
> 2277: BUILDSYS_SHARED_LIB: command not found ./configure: line 2279: syntax
> error near unexpected token external'
> ./configure: line 2279: AM_GNU_GETTEXT(external)' $
>

autoconf is all based on M4, which is a macro language - and configure.ac
is sent through M4, and the result is configure. Any macroes not
recognized, will be put into the configure as is, hence you get "
BUILDSYS_SHARED_LIB: command not found". autoconf did not know how to
convert that single token into something else.


Where does autoconf find these macros?
2 locations: your system files, or the aclocal.m4 file.

your system files: macros appear in the /usr/[INSERT YOUR DISTRO THING
HERE]/autoconf/... when you install -dev packages

aclocal.m4  is usually created from a folder named m4 when you run
aclocal -I m4           <-  if your source-code contains a m4 folder, try
this command -  AUD_COMMON_PROGS   macro suggest that something like this
exists.


If there is a autogen.sh  file in the source-code, run that - it should
run   aclocal   autoconf    and what-ever other tools the developer has
used, examples be autoheader, automake, ...



Good luck

Stian Skjelstad

**Comment by starhawk64** [comment]
@Malvineous that er does make sense, admittedly :-/

@mywave82 --
Stian (or do you prefer something a bit more formal? I try to be respectful!) -- thank you a hundred million times :)

I am NOT a programmer. I'm a hardware guy. Things I can solder make sense to me... if I have to tell it what to do... well, even with people in real life that generally doesn't go very well :-/ you've provided an absolutely brilliant explanation, though, and a suggestion to follow up, and that is extraordinarily helpful.

I seem to recall seeing an 'autogen.sh' file in there somewhere, and wondering "oh gee what does that do?" before shrugging it off as something ancillary and going off elsewhere. I'll see if I can't clean things up a bit and then run that. Right now I'm not at my computer (on my phone) but I'll keep everyone posted.

FWIW... all I know about compilation is from doing it zillions of times with an Xorg driver. Look up the 'openchrome' driver's bug #91966 (I'll warn you that it's quite a long read!) for that story, which involves a particularly unusual hardware configuration in a "thin client" system (for yhe uninitiated, basically it's a networked KVM for a remote session on a server somewhere else... or, if you're familiar with timesharing setups and RS232 terminals from the 1970s, eg the Wyse 50, it's the modern equivalent)... specifically a Wyse Cx0-series box, sometimes referred to simply as a Wyse C-series. Wyse had weird version numbering... they still do, TBH, but now that they're part of Dell it's a bit more straightforward.

...whoops, I'm rambling. It happens :-/ I'll stop for now, though... I'll let you folks know how the autogen thing goes.

**Comment by starhawk64** [comment]
@mywave82 -- Back in front of the machinery :) Cleaned things up, and sure enough, autogen.sh is in there... I ran it, it's done some things, but it's not compiled the whole bit...

The contents of the file in question are very simple --
`
#!/bin/sh
aclocal -I m3 || exit 1
autoconf || 1
autoheader || exit 1`

I see a new 'configure' file; should my next steps be the usual (i.e. -- ./configure -- make -- make install ) or something else...? Just making sure before I screw something up.

**Comment by Malvineous** [comment]
Yes `autogen.sh` will have created `configure` so run that next and see if it succeeds or produces errors.

**Comment by starhawk64** [comment]
It chokes... it's looking for a 'glib-2.0' package, which in Ubuntu is called 'gir1.2-glib-2.0' -- and since the naming convention is different, it sadly fails to find the package.

Suggestions...?

**Comment by mywave82** [comment]
The files is searches for has the name across distroes. Install the
glib2.0-dev package

**Comment by starhawk64** [comment]
```
$ apt search glib-2.0-dev
i   libspice-client-glib-2.0-dev                                           - GObject for communicating with Spice servers (development files)
$ 
```

**Comment by starhawk64** [comment]
Helps not to have typos... ;) libglib2.0-dev installed. Next hurdle... :-/

`$ ./configure
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking whether byte ordering is bigendian... no
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... no
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking operating system type... Linux
checking whether the C/C++ compiler supports -Wtype-limits... yes
checking whether the C/C++ compiler supports -Wno-stringop-truncation... yes
checking whether the C++ compiler supports -Woverloaded-virtual... yes
checking whether byte ordering is bigendian... (cached) no
checking whether ln -s works... yes
checking for rm... /bin/rm
checking for mv... /bin/mv
checking for cp... /bin/cp
checking for ar... /usr/bin/ar
checking for ranlib... /usr/bin/ranlib
checking for windres... no
checking for library containing pthread_create... -lpthread
checking for GLIB... yes
checking for GMODULE... yes
checking for GIO... yes
checking for QTCORE... no
configure: error: Package requirements (Qt5Core >= 5.2) were not met:

No package 'Qt5Core' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables QTCORE_CFLAGS
and QTCORE_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
$ sudo apt-get install libqt5core5a
Reading package lists... Done
Building dependency tree
Reading state information... Done
libqt5core5a is already the newest version (5.12.8+dfsg-0ubuntu1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
$`

**Comment by mywave82** [comment]
You need the -dev package for the qt stuff to.

-dev is development, contains the files needed in order to compile develop
for each of the libraries you install it for


Stian (both Stian and mywave/mywave82 is ok)

**Comment by starhawk64** [comment]
Well yes... but neither apt nor Google want to give me a package name... hence the question... ;)

**Comment by mywave82** [comment]
Try to search for qtbase5-dev

Stian

**Comment by starhawk64** [comment]
Well this is a bit hilarious... and annoying, TBH... before anyone asks, the answer is YES and the version numbers match.

`$ ./configure
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking whether byte ordering is bigendian... no
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... no
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking operating system type... Linux
checking whether the C/C++ compiler supports -Wtype-limits... yes
checking whether the C/C++ compiler supports -Wno-stringop-truncation... yes
checking whether the C++ compiler supports -Woverloaded-virtual... yes
checking whether byte ordering is bigendian... (cached) no
checking whether ln -s works... yes
checking for rm... /bin/rm
checking for mv... /bin/mv
checking for cp... /bin/cp
checking for ar... /usr/bin/ar
checking for ranlib... /usr/bin/ranlib
checking for windres... no
checking for library containing pthread_create... -lpthread
checking for GLIB... yes
checking for GMODULE... yes
checking for GIO... yes
checking for QTCORE... yes
checking for QT... yes
checking for shared library system... ELF
checking whether make sets $(MAKE)... yes
checking for a BSD-compatible install... /usr/bin/install -c
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for a sed that does not truncate output... /bin/sed
checking whether NLS is requested... yes
checking for msgfmt... /usr/bin/msgfmt
checking for gmsgfmt... /usr/bin/msgfmt
checking for xgettext... /usr/bin/xgettext
checking for msgmerge... /usr/bin/msgmerge
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for shared library run path origin... done
checking for CFPreferencesCopyAppValue... no
checking for CFLocaleCopyCurrent... no
checking for GNU gettext in libc... yes
checking whether to use NLS... yes
checking where the gettext function comes from... libc
checking for AUDACIOUS... no
configure: error: Cannot find Audacious 4.0; have you installed Audacious yet?
$
`

**Comment by mywave82** [comment]
audacious-dev ;)

**Comment by starhawk64** [comment]
You'd think I'd learn... :-/

Next one... oy... three in one, it wants a hat trick.

`$ ./configure
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking whether byte ordering is bigendian... no
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... no
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking operating system type... Linux
checking whether the C/C++ compiler supports -Wtype-limits... yes
checking whether the C/C++ compiler supports -Wno-stringop-truncation... yes
checking whether the C++ compiler supports -Woverloaded-virtual... yes
checking whether byte ordering is bigendian... (cached) no
checking whether ln -s works... yes
checking for rm... /bin/rm
checking for mv... /bin/mv
checking for cp... /bin/cp
checking for ar... /usr/bin/ar
checking for ranlib... /usr/bin/ranlib
checking for windres... no
checking for library containing pthread_create... -lpthread
checking for GLIB... yes
checking for GMODULE... yes
checking for GIO... yes
checking for QTCORE... yes
checking for QT... yes
checking for shared library system... ELF
checking whether make sets $(MAKE)... yes
checking for a BSD-compatible install... /usr/bin/install -c
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for a sed that does not truncate output... /bin/sed
checking whether NLS is requested... yes
checking for msgfmt... /usr/bin/msgfmt
checking for gmsgfmt... /usr/bin/msgfmt
checking for xgettext... /usr/bin/xgettext
checking for msgmerge... /usr/bin/msgmerge
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for shared library run path origin... done
checking for CFPreferencesCopyAppValue... no
checking for CFLocaleCopyCurrent... no
checking for GNU gettext in libc... yes
checking whether to use NLS... yes
checking where the gettext function comes from... libc
checking for AUDACIOUS... yes
checking for XML... yes
checking for ADLIB... no
configure: WARNING: AdLib support disabled due to missing dependency: adplug
checking for CDIO... no
configure: WARNING: audio CD support disabled due to missing dependency: libcdio >= 0.70 libcdio_cdda >= 0.70 libcddb >= 1.2.1
checking for LIBFLAC... no
configure: error: Missing dependency for FLAC support: flac >= 1.2.1
$ 
`

**Comment by Malvineous** [comment]
Why is it looking for FLAC?!  Are you compiling the plugin or Audacious itself?

Unless configure supports a `--without-flac` option then I guess your only option is to install those things plus the `-dev` variants.

**Comment by starhawk64** [comment]
It's the audacious-plugins package.

I'll get to that later today or tomorrow... today is being difficult, sorry!

**Comment by Malvineous** [comment]
Gonna close this just so it's not sitting around unresolved.  Feel free to reopen if you find something wrong on the AdPlug side.
