### ISSUE TITLE
Night Owl BBS Shareware CD-ROMs Adlib .ROL songs not supported

### ISSUE THREAD

**Issue by HunterZ** [adplug/adplug#121]
Tried several old songs from here, but none of them seem to be supported?
http://www.retroarchive.org/cdrom/nightowl-005/050A/index.html

Edit: Same issue with the .zip file downloaded from here: http://vgmpf.com/Wiki/index.php/AdLib_(DOS)#Game_Rip

Is it an issue of needing to feed in an instrument bank file? If so, how is that done?

**Comment by HunterZ** [comment]
Update: Figured it out - it's a combination of filenames with spaces not being supported (even with escaping or quoting) and needing `standard.bnk` in the same directory as the song file.

**Comment by Malvineous** [comment]
Works fine for me with spaces in both the filename and the folder (tested with adplay), but you're right, you need `standard.bnk` in the current directory for it to work.  I don't think there's any way around that as there isn't really a facility to provide any error messages if a file can't be opened.

**Comment by HunterZ** [comment]
The space thing is probably my own setup then, as I'm using a version of `adplay-unix` hacked to run the disk output on Windows, and I'm running it from Git Bash. Closing the issue, as I don't think there's anything to do here.
