### ISSUE TITLE
CPlayer runs DUNE1.ADL forever

### ISSUE THREAD

**Issue by HunterZ** [adplug/adplug#122]
`DUNE1.ADL` (in attached `.zip` archive) contains many small subsongs, plus longer 10 minute and 5 minute subsongs.

For some reason it seems to get stuck on the 10 minute subsong 2 forever in both `adplay-unix` and the foobar2000 AdPlug plugin, even when the once / don't loop option is specified. This is bad when using the disk writer output, because it would just run until the disk is full!

Unfortunately the order/pattern/row stuff doesn't seem to be supported for this format, so it's impossible to tell if it's getting caught up in some internal looping structure (which is my guess, as it's meant to be a looping game song).

[DUNE1.zip](https://github.com/adplug/adplug/files/5397005/DUNE1.zip)

**Comment by Malvineous** [comment]
Yeah this is a known issue with a lot of file formats.  I'm not sure why it happens but if anyone can work it out, patches are welcome!  It seems to be in the replayer code not signalling when the end of the song is reached, for a number of different file formats.

**Comment by HunterZ** [comment]
As a crude workaround, I've modified `output.cc` in adplay-linux to default `playing` to `true` and then use `playing &= p->update();` instead of directly storing the return value. This lets me stop playback at any time by manually setting `playing` to `false`.

**Comment by miller-alex** [comment]
It's been a while since I posted a possible solution in #126. Have you tested it?

Any comments? Does it make sense to merge that?
