### ISSUE TITLE
Rad2 player bug for Rad1 file - proposed fix

### ISSUE THREAD

**Issue by yoyofr** [adplug/adplug#128]
Hello,

there is an issue in the rad2 init which prevent correct rad1 playback.
Need to change one line (last line below)

```
void RADPlayer::Init(const void *tune, void(*opl3)(void *, uint16_t, uint8_t), void *arg) {

	Initialised = false;

	// Version check; we only support version 1.0 and 2.1 tune files
	uint8_t ver = *((uint8_t *)tune + 0x10);
	if (ver != 0x10 && ver != 0x21) {
		Hertz = -1;
		return;
	}
	Version = ver >> 4;
	UseOPL3 = (Version >= 2);  //was before -> UseOPL3 = ver>=2;
```

**Comment by Malvineous** [comment]
@devinacker Is this something you are able to review?

**Comment by devinacker** [comment]
The change looks okay to me - it should indeed be checking only the major version (i.e. you could also do `ver >= 0x20`)

**Comment by binarymaster** [comment]
> there is an issue in the rad2 init which prevent correct rad1 playback

@yoyofr what file are you using to reproduce this problem? Please name it or give a link, so I can test.
