### ISSUE TITLE
silence or immediate exit for some apparently valid .mid files

### ISSUE THREAD

**Issue by cjfp** [adplug/adplug#165]
I am trying to play some .mid files from TIE Fighter.

I am using the archive [here](http://www.mirsoft.info/wogm_download.php?data=YTozOntpOjA7czo0OiIyNzMwIjtpOjE7aToxNjc1NDY4OTExO2k6MjtpOjM7fQ==).

adplay works for all of the .mid files except the ones in the "Mission combat songs" folder.  In that folder,

`$ adplay TIE\ Fighter\ -\ Approaching\ enemies.mid`

gives me extended silence.

`$ adplay -o TIE\ Fighter\ -\ Approaching\ enemies.mid`

exits immediately.

foobar2000 can play these files using the non-adplug foo_midi component but the sound is not right.  However I think this is evidence that the files themselves are not corrupt or malformed.

I am using libao with Cygwin if it matters.

**Comment by mywave82** [comment]
This MIDI file is type 1. Support was added by this patch 30bfa25f80106b83b0ecee1a095cb1608f3fa5cb

**Comment by cjfp** [comment]
Yes, the patch works for me, thank you!
