### ISSUE TITLE
Adlib Tracker II issue

### ISSUE THREAD

**Issue by wothke** [adplug/adplug#168]
It seems to me that "recent" improvements in the "a2m.cpp" impl are breaking things that did "work" before.

I had been previously using some older AdPlug version (from around 2018) and just updated to the current head version. I then noticed that songs that play with the older version no longer play now. 

In test cases like "cracker.a2m" and "crack it.a2m" the problem seems to be the added input validation:

```
  for (i = 0; i < length; i++)
    if ((order[i] & 0x7f) >= numpats) {		// invalid pattern in order list
      delete [] org;
      fp.close(f);
      return false;
    }
```
and removing that check lets  those songs again play.

PS: are there any plans to add support for the version 9 format? (most of the files on modland seem to be in 
that newer format)

**Comment by mywave82** [comment]
> PS: are there any plans to add support for the version 9 format? (most of the files on modland seem to be in
that newer format)

This is ticket #14

**Comment by mywave82** [comment]
https://modland.com/pub/modules/Ad%20Lib/AdLib%20Tracker%202/Nula/cracker.a2m
https://modland.com/pub/modules/Ad%20Lib/AdLib%20Tracker%202/Subz3ro/crack%20it.a2m
