### ISSUE TITLE
Support loading from memory and recognizing file types

### ISSUE THREAD

**Issue by dv1** [adplug/adplug#17]
Right now, it is necessary to know a file name. If however the song data is in a memory block, this is impractical. It would also be very useful to have a "detect" function to determine if such a memory block contains data that one of the adplug players can bplay, and to know which file type it is.

**Comment by Malvineous** [comment]
How would this work for those file formats that need to load additional files, such as those that store the instruments in a separate file to the song?  What about the IMF format, which is played at a different tempo depending on whether the filename ends in .imf or .wlf?

**Comment by binarymaster** [comment]
> How would this work for those file formats that need to load additional files

They should not be automatically detected, except the song can be played with default instrument set. Also there is a plenty of formats which have no signatures in header - some of them can be detected by checking data size and value ranges. In some cases this can lead to false positives, just deal with it.

> What about the IMF format, which is played at a different tempo depending on whether the filename ends in .imf or .wlf?

As always, calculate data checksum and use database.

**Comment by Malvineous** [comment]
You can already detect and play a file from a memory block, but you need to specify a filename as this is required by the detection code.  The file doesn't have to exist, it is only a string, but the detection code checks the filename extension and uses that to help identify the format.  Without the filename (even a made up filename) the code won't detect files properly.

Here is some code I am using for the XMMS2 plugin that reads the file into a memory buffer and passes the buffer to AdPlug:
```
#include <binio.h>
#include <binstr.h>
class CProvider_Mem: public CFileProvider
{
	private:
		uint8_t *file_data;
		int file_size;

	public:
		CProvider_Mem(uint8_t *file_data, int file_size) :
			file_data(file_data),
			file_size(file_size)
		{
		}

		virtual binistream *open(std::string filename) const;
		virtual void close(binistream *f) const;
};

binistream *CProvider_Mem::open(std::string filename) const
{
	binisstream *f = new binisstream(this->file_data, this->file_size);

	if (!f) return 0;
	if (f->error()) { delete f; return 0; }

	// Open all files as little endian with IEEE floats by default
	f->setFlag(binio::BigEndian, false);
	f->setFlag(binio::FloatIEEE);

	return f;
}

void CProvider_Mem::close(binistream *f) const
{
}
```
It's used like this:
```
		CProvider_Mem prMem(content, len);
		player = CAdPlug::factory(filename, opl, CAdPlug::players, prMem);
```

**Comment by kotc** [comment]
thanks for the code! it works nicely, though some tunes sound weird or crash when loaded that way (for example datura.xad crashes in __bmf_convert_stream).

**Comment by kotc** [comment]
and apparently breakes .vgm because filesize() returns allocated size + 1

**Comment by kotc** [comment]
or it's f->pos() method returning +1 more. in .sop it breakes:
                if (fp.filesize(f) - f->pos() < track[i].size)
by one (checked in both cases by allowing one more byte, tunes played then)

**Comment by kotc** [comment]
and .rol's load_voice_data() because it tries to use cfileprovider from context (which is _mem instead of normal file load). checked by initializing     binifstream *bnk_file = new binifstream(bnk_filename); in the routine, plays fine.
which means secondary loaders that is using cfileprivider context will fail when tune was loaded from mem

**Comment by kotc** [comment]
and in .mus (fp.filesize(f) < (unsigned)(HEADER_LEN + dataSize)))

**Comment by Malvineous** [comment]
Yep, like I said in my original reply, how would it work if additional files need to be loaded?  That question is still unanswered as it will require code changes to many of the format handlers as you've discovered.

I haven't experienced any crashes but haven't tried a lot of those formats you're using.  Sounds like it could be a bug in libbinio's `binisstream`.  If you can find the bug and fix it, please submit a PR against libbinio so we can fix it.

Loading additional files will be a bigger architectural change and one I'm more than happy to consider if someone writes a nice neat patch for it, but probably not something I will be implementing myself.  (I just maintain AdPlug, I don't work on it much.)

**Comment by kotc** [comment]
yeah, seems so: following code:
```
#include <stdio.h>
#include <stdlib.h>
#include "adplug/fprovide.h"
extern "C" void adplug_kctest();
/////###############
void adplug_kctest() {
 int size=64;
 char *buf=(char *)malloc(size);
 CProvider_Mem pm((unsigned char *)buf, size);
 binistream *f = pm.open("somefile"); if(!f) { printf("pm.open failed\n"); return; }
 FILE *flog=fopen("/tmp/adplug.log","w");
 if(flog) { fprintf(flog,"s:%d fs:%d\n", size, pm.filesize(f)); }
 delete f;
 free(buf);
 if(flog) { fprintf(flog,"meow\n"); }
 if(flog) { fclose(flog); }
}
```
produces: s:64 fs:63. so probably CProvider_Mem::open() would need +1 on the size param. seems easiest (and doesnt require patching libbinio nor workarounding .filesize() in fprovider.c

**Comment by kotc** [comment]
yup. i have just tried. it fixes all crashes as well. so the only problem remains secondary files. best way would be using user supplied function (via function pointer, with fallback to plain file loader, but new one, outside of cfileprovider context!)

code added to src/fprovide.cpp:
```
/***** CProvider_Mem *****/

#include <binstr.h>

binistream *CProvider_Mem::open(std::string filename) const
{
        // requires +1 over supplied size for off-by-one filesize() bug
        binisstream *f = new binisstream(this->file_data, this->file_size + 1);

        if (!f) return 0;
        if (f->error()) { delete f; return 0; }

        // Open all files as little endian with IEEE floats by default
        f->setFlag(binio::BigEndian, false);
        f->setFlag(binio::FloatIEEE);

        return f;
}

void CProvider_Mem::close(binistream *f) const {
 binifstream *ff = (binifstream *)f;  if(f) { delete ff; }
}
```

code added to src/fprovide.h:
```
#include <binstr.h>
class CProvider_Mem: public CFileProvider
{
  private:
    unsigned char *file_data;
    int file_size;

  public:
    CProvider_Mem(unsigned char *file_data, int file_size) :
      file_data(file_data),
      file_size(file_size)
    {}

    virtual binistream *open(std::string filename) const;
    virtual void close(binistream *f) const;
};
```

and that makes it possible to use mem loader. again, tunes with secondary files would require changes similar to:
```
- binistream *f = fp.open(fname);
- fs=fp.filesize(f)
- fp.close(f);
+ binifstream *f = new binifstream(fname);
+ f->seek(0, binio::End); fs = f->pos(); f->seek(0, binio::Set);
+ f->close();
```
but there is only a few that need it.

**Comment by binarymaster** [comment]
Well, it would be better to find this bug inside libbinio and fix it.

Since it firstly occured here, it may occur in some other places in future. :thinking:

**Comment by mywave82** [comment]
I hunted this bug down (OpenCubicPlayer is switching to memory-mapped buffers, and hits this bug hard)

https://github.com/adplug/libbinio/pull/8

**Comment by Malvineous** [comment]
@mywave82 Are you sure this fixes the bug?  All I can see is that it would stop setting an error flag when you did a seek to EOF, but otherwise there is no change.  Am I missing something?

**Comment by mywave82** [comment]
The readstring function checks for EOF after each byte fetch, so it will only fetch a single byte and report zero.

Filesize() triggers this pattern.

**Comment by mywave82** [comment]
You can also maybe add to clear eof error flag if a seek has moved the readpointer into the readable area

**Comment by mywave82** [comment]
```c++
#include <binio.h>
#include <binstr.h>
#include <cstdlib>
#include <string.h>
#include <adplug/adplug.h>
#include <adplug/fprovide.h>
#include <string.h>

int main(int argc, char *argv[])
{
        binisstream *f = new binisstream((void *)"foobar", 6);
        long size;
        char test[6] = {1,2,3,4,5,6};

        f->seek(0, binio::End);
        size = f->pos();
        f->seek(0);

        if (f->readString(test, size) != 6)
        {
                fprintf (stderr, "readString() return code indicicates a problem\n");
        }

        if (memcmp(test, "foobar", 6))
        {
                fprintf (stderr, "Wrong data fetched\n");
        }

        return 0;
}
```

**Comment by Malvineous** [comment]
Ah, now I understand, thanks for the explanation!

**Comment by Malvineous** [comment]
Looks like this is all good now, closing.  Feel free to reopen (or preferably open a new issue) if there is still a problem.
