### ISSUE TITLE
Quality Assurance issue

### ISSUE THREAD

**Issue by toralf** [adplug/adplug#2]
Hello,

a Quality Assurance issue was reported by the build system of my Gentoo Linux tinderbox [1] while building a Gentoo package containing your software.

Such reported issues are sometimes correct.
Otherwise just drop this mail.
OTOH it would be interesting why the issue is wrong.

=============================================================================
[1] volumes/amd64-stable_20150713-232025/var/log/portage/elog/media-libs:adplug-2.2.1:20150715-102430.log
    b.g.o: https://bugs.gentoo.org/buglist.cgi?query_format=advanced&resolution=---&short_desc=media-libs%2Fadplug&short_desc_type=allwordssubstr
    sound
=============================================================================

QA: other
QA Notice: Package triggers severe warnings which indicate that it
           may exhibit random runtime failures.
mid.cpp:873:53: warning: iteration 14u invokes undefined behavior [-Waggressive-loop-optimizations]
Please do not file a Gentoo bug and instead report the above QA
issues directly to the upstream developers of this software.
Homepage: http://adplug.sourceforge.net

**Comment by Malvineous** [comment]
I have looked at the code in question but cannot see what the problem is.  The array is 16 elements in size, so there should be no problem writing to index 14.

**Comment by Malvineous** [comment]
Just realised that this problem is not with writing to array elements, but reading from them.  The FM patches come from an array that is only 14 elements long, but the code copies 16 elements into a 16 element array.
