### ISSUE TITLE
MinGW: libtool "error: can't build x86_64-w64-mingw32 shared library unless -no-undefined is specified"

### ISSUE THREAD

**Issue by mnhauke** [adplug/adplug#205]
Cross-compiling libadplug for Windows via the MinGW64 toolchain with gcc from a Linux system works fine.

The only error I encountered was the missing "-no-undefined" in LDFLAGS.
`libtool:   error: can't build x86_64-w64-mingw32 shared library unless -no-undefined is specified`

[libbinio](https://github.com/adplug/libbinio) is affected as well.

I used the following patches to fix/workaround the issues:
https://pmtu.de/.dump/mingw64-libadplug-libtool.patch
https://pmtu.de/.dump/mingw64-libbinio-libtool.patch

**Comment by mywave82** [comment]
Thank you for the contribution!
