### ISSUE TITLE
ROL tracks display \roll\default

### ISSUE THREAD

**Issue by mohd-akram** [adplug/adplug#211]
I'm playing ROL tracks via Audacious and it falls back to using the description if a title is not available. In the case of ROL tracks it seems most have \roll\default, and in that case the filename would have been more useful. Perhaps `getdesc` should return an empty string if the description is \roll\default?

**Comment by binarymaster** [comment]
Should be fixed in 494a2bd6c8a / `adplug.2.3.4-beta751.nupkg`, thanks for reporting!

If you know any ROL tracks that have a custom (not default) description, please let me know, because I've never encountered these.

**Comment by mohd-akram** [comment]
I think I saw a couple somewhere, but it's very rare.
