### ISSUE TITLE
update winamp plugin to latest adplug

### ISSUE THREAD

**Issue by winamp-girl** [adplug/adplug#215]
Hi

Is it possible to update the winamp plugin to use latest Adplug?
The latest version was in the year 2017

https://github.com/adplug/winamp/releases/tag/winamp-1.8.2

Download latest winamp (5.9.2) at the bottom of this page

https://about.winamp.com/press/article/winamp-open-source-code

**Comment by binarymaster** [comment]
Duplicate of https://github.com/adplug/winamp/issues/25.
