### ISSUE TITLE
File descriptor leak in CadtrackLoader::load()

### ISSUE THREAD

**Issue by jlindgren90** [adplug/adplug#25]
At adtrack.cpp line 65 there is a check that the instruments file (instf) is exactly 468 bytes.  If not, CadtrackLoader::load() returns false without closing the file.

Found by static analysis on Audacious (which includes a copy of adplug).

**Comment by binarymaster** [comment]
Probably it's already fixed, see line 65:

https://github.com/adplug/adplug/blob/7bc64fab5cb7f18aca935cfbc46e40802f0d09fc/src/adtrack.cpp#L65

```cpp
  if(!instf || fp.filesize(instf) != 468) { fp.close(f); return false; }
```

**Comment by jlindgren90** [comment]
I think `f` and `instf` are different files.  There are separate fopen() calls on lines 47 and 64.

**Comment by binarymaster** [comment]
Yes... didn't see it for the first time. `instf` file should be closed.

**Comment by binarymaster** [comment]
@jlindgren90 which software do you use for code static analysis?

**Comment by jlindgren90** [comment]
@binarymaster I use Coverity.
