### ISSUE TITLE
DUNE6.ADL (and others DUNE files) not working

### ISSUE THREAD

**Issue by loki666** [adplug/adplug#33]
don't know if it's related to #6 
test DUNE19.ADL is working though...

**Comment by Malvineous** [comment]
What do you mean by "not working"?  Can you provide any more details about the problem?  Which files don't work, what happens when they don't work, how the behaviour is different to #6 etc.

**Comment by loki666** [comment]
Well, it is different from #6 because AdPlug doesnt SEGFAULT (but maybe this has already been fixed since).
It's like AdPlug just skip it or the file doesnt contains any songs, It open the file, recognize it as an ADL Westwood file, and then stops.

Here is the file
[DUNE6.ADL.zip](https://github.com/adplug/adplug/files/476260/DUNE6.ADL.zip)

**Comment by binarymaster** [comment]
Which way you're trying to play the file? Linux command-line, Winamp plugin, DOS AdPlay?

**Comment by loki666** [comment]
sorry, I'm using the linux command-line

**Comment by binarymaster** [comment]
Ok. Westwood ADL files are multi-track. The first track in the file is often empty.

Try to specify a song index 7 (or 6 if indexes are from zero).

**Comment by loki666** [comment]
Ah, ok thanks, I'll give it a shot

Is there a way to "detect" which subsong is the correct one? Or is it always 7?

**Comment by binarymaster** [comment]
There is no such algorithm. You need to listen each subsong to know that.

I'm using Winamp plugin which shows the count of subsongs.

**Comment by loki666** [comment]
ah f*ck!
It works thanks for help.
