### ISSUE TITLE
Add support for the VGM file format

### ISSUE THREAD

**Issue by sdsnatcher** [adplug/adplug#38]
There are many songs out there [dumped in the VGM file format for the OPL3](https://vgmrips.net/packs/chip/ymf262). Amongst them are gems like the Cybersphere, Miwaku no Chousho and Puyo Puyo 2 soundtracks.

The VGM file specs are very simple and can be obtained [here](https://vgmrips.net/wiki/VGM_Specification) and [here](http://www.smspower.org/Music/VGMFileFormat).

Of course only the YMF262 and YMF278 chips will be supported by Adplug for VGM.

**Comment by binarymaster** [comment]
As long as I know, YMF278 (OPL4) is not supported by AdPlug emulators.

Only YM3812 (OPL2) and YMF262 (OPL3). (correct me if I'm wrong)
