### ISSUE TITLE
Out-of-bounds memory access

### ISSUE THREAD

**Issue by cspiegel** [adplug/adplug#4]
In src/adl.cpp, around line 2382, _trackEntries is looped over from 199 to 0.  However, _trackEntries has only 120 elements, so this winds up accessing beyond the end of the array.

**Comment by Malvineous** [comment]
Happy to accept a patch if you're able.  Even better if you can run the test code and include updated tests (only if your patch causes the existing tests to fail.)

**Comment by cspiegel** [comment]
I wasn't certain if the allocation was wrong or the subsong checking was wrong; after some searching about the format of ADL files, it looks like the subsong checking is at fault, so I'll make a fix for that.

**Comment by Malvineous** [comment]
Great, many thanks!
