### ISSUE TITLE
Missing CMF Effects

### ISSUE THREAD

**Issue by thecoreyburton** [adplug/adplug#45]
"I have noticed another difference: the lead/pad voice has no chorus-like effect in AdPlug, so the same voice sounds better using SBFMDRV driver. But this is for another issue." - @binarymaster @ https://github.com/adplug/adplug/issues/41

In addition to this comment, whilst I was listening to "song_d.xr0" I noticed that notes also seem to be lacking another effect as well. Just after 4:14 in the following link, you'll hear the last note of each small section is repeated several times and gradually fades out: https://www.youtube.com/watch?v=6It3k8sodu4

Whereas when using AdPlug this effect seems to be missing and the notes are repeated at a consistent, full volume.

**Comment by Malvineous** [comment]
This is intentional.  The CMF note data is standard MIDI, and MIDI allows note-on events to have a velocity value, which controls the volume that note sounds at.

However both SBFMDRV and Xargon ignore note velocities and play each note at maximum velocity.  This means that although a number of songs contain volume effects like the fade out in `song_d.xr0`, that effect is never heard in the game.  You can verify this by loading the shareware version of Xargon and choosing to watch the demo/preview from the main menu.  You will hear that the fade out effect in `song_d.xr0` is not present, and the notes are simply repeated at full volume.

Since the official players ignore these events I chose to make the AdPlug CMF player do the same, so that the songs would more closely match the way they were heard in the original game.  You can however re-enable this effect if you wish, by uncommenting [line 39 in cmf.cpp](https://github.com/adplug/adplug/blob/master/src/cmf.cpp#L39).

I am not sure what player was used to create the YouTube video, but it definitely wasn't SBFMDRV or Xargon itself!

**Comment by thecoreyburton** [comment]
Ah, yep. You're right. I tried both using the game itself and playcmf.exe and there were no velocity effects present in either of them, so you can disregard my comment regarding the fade. If you wanted to you could probably add a checkbox for MIDI velocities on CMF playback that is disabled by default so there's an additional listening experience available, but that's more of a completely unnecessary enhancement and isn't really important. It's covered it terms of accuracy and that's what counts!

You can consider my comments on the issue resolved and leave this open solely for @binarymaster's findings then.

**Comment by Malvineous** [comment]
It was originally too much effort for me to make it configurable at runtime so I never bothered, but as always, patches are welcome!

I'll close this issue since there's not really any work to do on it, but comments can still be made if needed.

**Comment by binarymaster** [comment]
> I have noticed another difference: the lead/pad voice has no chorus-like effect in AdPlug, so the same voice sounds better using SBFMDRV driver.

This effect is achieved by using 2 channels with same melody, and the second channel is transposed a bit by a control event.

![image](https://cloud.githubusercontent.com/assets/578406/20037628/34c4f92e-a434-11e6-97b2-0dd642a69e37.png)

"Transpose Down" is CMF-specific control event 0x69. Seems like it's not properly interpreted, or just not implemented.

**Comment by thecoreyburton** [comment]
How easy would something like that be to implement into adplug?

**Comment by Malvineous** [comment]
It's handled and implemented in [cmf.cpp line 518](https://github.com/adplug/adplug/blob/master/src/cmf.cpp#L518).  `iTranspose` is the number [from the control event](https://github.com/adplug/adplug/blob/master/src/cmf.cpp#L784), positive for up, negative for down (e.g. `-12` using the event in the screenshot above.)  It's possible the formula is wrong as I had no easy way of testing it when I originally wrote it.

**Comment by binarymaster** [comment]
I've added a fix for transpose effect:
- Note transposition is related to a MIDI channel (pretty same as Pitch Bend), not a whole song
- Division by an integer (`this->iTranspose / 128`) was incorrect

However there is another unresolved problem - transpose controller must modify already playing note frequencies in realtime. The same goes for Pitch Bend events.

Also I attached sample CMF files that use dynamic frequency changes:
- 1.cmf - uses vibrato at 0:52
- 2.cmf - uses portamento-down at 0:57

[CMF.zip](https://github.com/adplug/adplug/files/598669/CMF_zip.txt)

**Comment by thecoreyburton** [comment]
Thank you! Once again, if you're able to provide me with a build of the Winamp plugin with this fix (and the missing note fix) applied, I'll happily do some more testing on a wider variety of tracks to see if I notice any remaining or new obscurities / problems.

**Comment by binarymaster** [comment]
@thecoreyburton ok!

[in_adlib.zip](https://github.com/adplug/adplug/files/602903/in_adlib.zip)

**Comment by thecoreyburton** [comment]
Thank you. I'll report back if I find or notice anything.

**Comment by thecoreyburton** [comment]
It's been about two weeks and I haven't noticed anything (any obscurities seem to match up to the hardware as far as I can tell). If you want me to check any songs specifically and compare then I'd be happy to, otherwise thank you. I think you've solved both my problems.

**Comment by binarymaster** [comment]
TODO:

Finish transpose effect implementation ([`cmf-transpose-fix`](https://github.com/adplug/adplug/tree/cmf-transpose-fix) branch) to pass the tests.
