### ISSUE TITLE
Merge Winamp distribution page in with main page

### ISSUE THREAD

**Issue by Malvineous** [adplug/adplug#50]
Historically, the Winamp plugin could not be distributed through SourceForge as it used the MAME OPL synth, which was not compatible with SF's open-source hosting policy.  A separate website was set up to distribute binary releases of the Winamp plugin for this reason.

Now we are hosting on GitHub there is no such restriction, so it would be nice to merge the old Winamp-only website in with the main AdPlug website so there is only one place to go for downloads.

The main AdPlug website is at http://adplug.github.io and is populated from the [adplug.github.io](https://github.com/adplug/adplug.github.io) repository.

The old Winamp-only page is currently hosted at http://www.shikadi.net/adplug/  There is no dynamic code on that page, so viewing the page source is all that is needed.

The merge process should probably go something like this:

1. Upload the historical Winamp plugins to the existing tags on the [GitHub release page for Winamp](https://github.com/adplug/winamp/releases)
2. I am not sure whether it is worth preserving the shikadi.net page for historical reasons, keeping it as a separate page on the new site.  I will leave this decision up to whoever does the merge.  If the page is not being kept, the MAME patches can be deleted.
3. Update the Winamp section on adplug.github.io with current information, perhaps with a link to the historical page if that is being kept.
4. Close this issue and I will then replace http://www.shikadi.net/adplug/ with a redirect to http://adplug.github.io.

@binarymaster Are you interested in having a go at this to learn how GitHub "pages" work?

**Comment by binarymaster** [comment]
This looks interesting :) I think it would be better to integrate contents of the old page to the new downloads page.

**Comment by binarymaster** [comment]
@Malvineous does the **License** block need to be moved to the new site or not?

**Comment by Malvineous** [comment]
That licence only applies to anything using the MAME code.  So if there's a link to the MAME patch or instructions for incorporating the MAME synth into the Winamp plugin, or if the Winamp plugin includes the MAME synth, then yes the licence should remain.  If the MAME patches are to be removed, then the licence won't be needed any longer.

I know we have introduced the DOSBox and Nuked OPL synths into the Winamp plugin but I can't remember whether the old MAME one has been removed or not.

Thanks for this!

**Comment by binarymaster** [comment]
Updated MAME emulator (non OSI compliant) is in `mame` branch:
https://github.com/adplug/adplug/blob/mame/src/fmopl.c

And there is an older LGPL version in `master` branch:
https://github.com/adplug/adplug/blob/master/src/fmopl.c

**Comment by Malvineous** [comment]
Hmm.  The CI version of the Winamp plugin uses the CI version of AdPlug, which is based on the `master` branch, so that version is fine - no special licence needed.

But the older versions (Winamp v1.7 maybe? And the older ones) would be using the MAME code, so they might still need the MAME licence.

Any good ideas about how this could be displayed on the site?  Is the MAME licence included in the .zip download for the old Winamp plugins?  If so, maybe we could get away with leaving it at that, and not having the licence on the web site since it no longer applies to new versions.

What do you think?

**Comment by binarymaster** [comment]
Since the new MAME emulator is not so important in recent versions, I did it this way: https://github.com/adplug/adplug.github.io/commit/fc974e00b440b96aea524ca8e83a9671009c312c

**Comment by Malvineous** [comment]
Perfect!

**Comment by binarymaster** [comment]
Thanks! Now you can make a redirect :)

**Comment by Malvineous** [comment]
Done, many thanks!
