### ISSUE TITLE
Let's release v2.3

### ISSUE THREAD

**Issue by Malvineous** [adplug/adplug#51]
In a few days it will be seven years since the last release, so it's probably time we made another official release of everything.

I'd like to avoid adding new code to the release so that what we release has been well tested already, so are there any major issues/bugs stopping us from releasing new versions of AdPlug, AdPlay, Winamp plugin, etc. based on the current git versions?

@binarymaster: I'm happy to do this release, but if you would like to have a go just let me know, I'm more than happy for you to handle it if you'd like to.  (If you would like to do it and there's nothing holding us back, please feel free to just go ahead and do it when you're able!  See [RELEASE](https://github.com/adplug/adplug/blob/master/RELEASE), and feel free to update that file if it's missing anything, like creating new git tags for the GitHub release system.)

**Comment by binarymaster** [comment]
Hello!

It's good idea to make new release.

There are some important issues which would be good to fix before releasing, for example:
- https://github.com/adplug/winamp/issues/11
- I didn't succeeded with building AdPlay/DOS (tried Open Watcom C), I think it needs build recipe to be updated

> I'm happy to do this release

Let you do this :) I'm now working hard on HERAD handler implementation, also I received a patch for adplug/winamp#11 from -=CHE@TER=-, but not tested it yet.

**Comment by binarymaster** [comment]
Any news?

I also noticed [there is no](https://github.com/adplug/winamp/releases) 1.9 release, although it was mentioned in README:
```
Since version 1.9 of this plugin, writing to a hardware OPL2 device is no
longer possible, due to the removal of the necessary API functions from
Windows.
```

**Comment by jlindgren90** [comment]
A new release would be great.  Even if it's just a new Git tag, it would give me a reference point for update our snapshot of adplug in Audacious.

**Comment by Malvineous** [comment]
@binarymaster Could you please take a look at the `NEWS` file I just updated, and add any user-visible changes you think are worth mentioning that I have missed?  (And remove any that you think aren't relevant for end-users.)  Thanks!

**Comment by binarymaster** [comment]
Ok! I think it would be good also to add HERAD to the release in **preliminary** mode (I'm gonna do it).

**Comment by badja** [comment]
The SoundFX Macs Opera CMF format doesn't appear to be mentioned in the NEWS file

https://github.com/adplug/adplug/pull/46

**Comment by binarymaster** [comment]
@Malvineous Done!

**Comment by binarymaster** [comment]
Also updated NEWS in [adplug/winamp](https://github.com/adplug/winamp), please take a look if something needs to be corrected.

**Comment by Malvineous** [comment]
Done!  https://github.com/adplug/adplug/releases

@binarymaster Looks like you did the last Winamp plugin release, do you want to do 1.9 as well?

**Comment by binarymaster** [comment]
Is it enough to create a tag, or does it require to change some values in build configuration script?

Also I saw in AppVeyor logs that it can produce tags:
```sh
"GitHub" deployment has been skipped as environment variable has not matched ("appveyor_repo_tag" is "false", should be "true")
```

**Comment by Malvineous** [comment]
Can't remember the details but it was something to do with deploying the latest git version to GitHub.  I think when AppVeyor uploaded the binary it created a new tag, which triggered a new compile which uploaded the binary, which created a new tag which triggered a new compile, etc, etc.

You should be fine to ignore it.  Just create the new tag, push it, then go into the GitHub releases page, create a new release, choose the tag you created and upload the .zip/exe.  I was going to suggest just copying the Appveyor built ones but it looks like they are a bit behind the latest git version, so maybe the CI build has broken there - not sure if you are able to fix that while you're at it?
