### ISSUE TITLE
Rare, idiosyncratic failure in CMF module

### ISSUE THREAD

**Issue by SoapGentoo** [adplug/adplug#57]
I am getting rare, hard to reproduce test failures in the CMF module, and only on macOS. These occur at a rate of about 10%, that is, I need 10 runs on average to produce one failure. In order to facilitate a generating a failure, you may want to run `while make check; do :; done`:

    Testing format: Creative Music File (CMF) - FAIL

Could this be related to an incomplete fix of https://bugs.gentoo.org/509660 ?

**Comment by binarymaster** [comment]
When some of tests fail, `playertest` would save `filename.cmf.test` in the same directory.

Do you able to provide that file for comparison with reference?

**Comment by SoapGentoo** [comment]
Here you go: [CMF.zip](https://github.com/adplug/adplug/files/1472473/CMF.zip)

**Comment by binarymaster** [comment]
![image](https://user-images.githubusercontent.com/578406/32846128-75d4b93e-ca37-11e7-9a33-9dcf188b708c.png)

Looks like some `if` condition doesn't work, probably something uninitialized.

**Comment by binarymaster** [comment]
This part of code doesn't get executed for some reason:

https://github.com/adplug/adplug/blob/3ed6617ec00022dfab574c27710d9071a6032c87/src/cmf.cpp#L748

**Comment by Malvineous** [comment]
Line 748 should only run when a note is already playing and the frequency gets changed (a pitch bend).  The OPL data in the .ref file suggests it's the initial note-on event that is missing, however the instrument for the channel is *not* set before the note-on happens in the .ref file.  It looks to me like the .ref file is actually wrong, and those events should not be appearing!

It should not be possible to sound a note on a channel before the instrument settings are loaded, so it almost looks like the problem files supplied by @SoapGentoo are actually the way it's meant to work!

**Comment by Malvineous** [comment]
Sorry disregard that last comment of mine, I misread the diff and was assuming it happened at the start of the song - I see the missing events are almost half way through, so it's not going to be a problem with the initial state.

**Comment by binarymaster** [comment]
It would be interesting to dump some variables during this bug, does it possible to reproduce it on AppVeyor / Travis?

**Comment by Malvineous** [comment]
There is a Mac build for Travis - if you push some changes to a temporary branch Travis should compile it and you can check the logs, then keep pushing to the branch as needed and delete the branch when you're done testing.

**Comment by binarymaster** [comment]
Currently testing this commit: https://github.com/adplug/adplug/commit/a01f9722bb38f61b8aea118cb724090774dcb2db.

Finally found interesting behaviour where test fails:
https://travis-ci.org/adplug/adplug/jobs/303033893 (see `after_failure.1` section)

@Malvineous  `iNoteStart` values becomes random for some reason, but must be the same each time.

In AppVeyor everything is ok:
```Update requested, iChannel = 3
iNumChannels = 6
chOPL[0], iMIDIChannel = 0, iNoteStart = 185
chOPL[1], iMIDIChannel = 2, iNoteStart = 187
chOPL[2], iMIDIChannel = 1, iNoteStart = 186
chOPL[3], iMIDIChannel = 5, iNoteStart = 184
chOPL[4], iMIDIChannel = 4, iNoteStart = 0
chOPL[5], iMIDIChannel = 3, iNoteStart = 183
Updating: iBlock = 4, iOPLFNum = 583
Write: a5 <- 47
Write: b5 <- 32
Update complete
```

**Comment by binarymaster** [comment]
Hmm... `this->iNoteCount` is not assigned anywhere?

**Comment by binarymaster** [comment]
@SoapGentoo please try retesting with updated `master` or `test` branches.

Test branch includes additional var dump, in case if something other is broken.

**Comment by SoapGentoo** [comment]
@binarymaster thanks for looking into this. I ran 400 loops of `make check`, and not one single failure. I consider this solved :+1:.
