### ISSUE TITLE
Make build system fully non-recursive

### ISSUE THREAD

**Issue by SoapGentoo** [adplug/adplug#58]
Hi @Malvineous 
when debugging Adplug earlier, I noticed that the build system is of the classic recursive type. This has a number of issues, such as implicit dependencies between directories (which Make cannot handle) and performance. If I send in a PR to make it fully non-recursive, would you be open to merging it?

**Comment by Malvineous** [comment]
I'd certainly consider it, but I wasn't aware there were problems with the current system.  Do you mean that having the build split into subdirectories is a problem?  The dependencies there seem to work fine, unless I'm missing something?

**Comment by SoapGentoo** [comment]
@Malvineous there are no direct problems leading to any failures, but a number of indirect problems. First, currently you depend on targets across directories, for instance here https://github.com/adplug/adplug/blob/master/test/Makefile.am#L9
This currently only works due to the way `SUBDIRS` is structured in the root `Makefile.am`. See https://lists.gnu.org/archive/html/automake/2009-08/msg00003.html for a nice treatment:

_A recursive build system must be designed to build component dependencies first before building the components. Thus, one limitation of a recursive build system is that it rather defines (or at least constrains) the directory structure that you must use. To get comps to be built before apps from within the app1 directory, you must build the comps directory structure from within the app1 directory._

Furthermore, the problem gets worse with 2017-era 24-core machines. Parallelization in Make can only happen **per instance**, and currently a new instance of Make is spawned for every subdirectory (because it's recursive). This leads to suboptimal parallelization, because Make cannot know the complete global dependency graph. Diego Elio Pettenò (a fellow Gentoo developer) has a nice treatment on why non-recursive build systems are so important in this day and age: https://blog.flameeyes.eu/2011/05/endless-recursion/

All of these problems can be solved by using a non-recursive Make solution.

**Comment by Malvineous** [comment]
I think the `SUBDIRS` thing is fine because we are only one level deep, but I take your point about the parallel build.  Speeding up builds would certainly be welcome.

In one of the links you posted there is a comment about a non-recursive build being impossible because the maintainer wanted the build output mixed in with the source files - I too would prefer not having to make a separate folder tree just for all the `.o` files.  Am I just misunderstanding and you can go non-recursive while leaving the `.o` and other files more or less where they are now?

If so, and the change works on Travis CI as well, then I would certainly be open to the change.

**Comment by SoapGentoo** [comment]
The `SUBDIRS` point still applies (even if just one level): your dependencies are not nested sub-directories, the fact that it works currently is more due to implicit behaviour than guarantee.

That part is due to a historic misunderstanding. Since Automake 1.10 it has been possible to dump the object file in the same dir as the source file (using the `subdir-objects` option), i.e. after fully compiling everything, the layout of object files and temporaries will look like it does today, so you don't need to be worried about that.

I will send in a PR to make the build system completely non-recursive.

**Comment by SoapGentoo** [comment]
If you would like to see such a failure, try 

	$ autoreconf -vif && ./configure && cd test && make check

for which I get

	make[1]: Entering directory '/home/soap/gitz/adplug/test'
	g++ -DPACKAGE_NAME=\"adplug\" -DPACKAGE_TARNAME=\"adplug\" -DPACKAGE_VERSION=\"2.3\" -DPACKAGE_STRING=\"adplug\ 2.3\" 	-DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DNDEBUG=/\*\*/ -DPACKAGE=\"adplug\" -DVERSION=\"2.3\" -DSTDC_HEADERS=1 	-DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 	-DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_GETOPT_H=1 	-I.  -I/usr/include/libbinio   -O2 -pipe -MT playertest.o -MD -MP -MF .deps/playertest.Tpo -c -o playertest.o 	playertest.cpp
	playertest.cpp: In function ‘bool diff(std::__cxx11::string, std::__cxx11::string)’:
	playertest.cpp:184:22: warning: ignoring return value of ‘char* fgets(char*, int, FILE*)’, declared with attribute 	warn_unused_result [-Wunused-result]
	     fgets(s1, 80, f1);
	                      ^
	playertest.cpp:185:22: warning: ignoring return value of ‘char* fgets(char*, int, FILE*)’, declared with attribute 	warn_unused_result [-Wunused-result]
	     fgets(s2, 80, f2);
	                      ^
	mv -f .deps/playertest.Tpo .deps/playertest.Po
	make[1]: *** No rule to make target '../src/.libs/libadplug.la', needed by 'playertest'.  Stop.

**Comment by Malvineous** [comment]
I take your point but I always figured you were required to do a full `make` before you could make a single subdirectory.  I guess the real problem is when you change code in `src/` but run your make in `test/`, the changes to `src/` will be quietly ignored.
