### ISSUE TITLE
Not Playing SOP Files

### ISSUE THREAD

**Issue by AntonZab** [adplug/adplug#60]
Not Playing SOP Files

https://drive.google.com/file/d/1yfmsGUKQXN834CnYrYgEJo3QzysJIYgz/view?usp=sharing

**Comment by binarymaster** [comment]
`ending.sop` and `op.sop` are corrupted files, probably dumped (incorrectly) from memory, I see 8-bit signed PCM samples here.

**Comment by binarymaster** [comment]
Or this is another format which supports digital samples.

**Comment by binarymaster** [comment]
Indeed, that's version 2 files with digital samples, added support in https://github.com/adplug/adplug/commit/73213e507f4e9fec4ead2f34503e665a1d682915.

**Comment by AntonZab** [comment]
Many thanks. When release latest version?
