### ISSUE TITLE
Support VS2017 using v141 toolset

### ISSUE THREAD

**Issue by Herschel** [adplug/adplug#68]
Currently appveyor only creates NuGet packages containing the v140 toolset (VS2015). It would be nice to support VS2017 with the v141 platform toolset.

There is a dependency on libbinio which also supports up to v140. https://github.com/adplug/libbinio/pull/7 would include v141 packages in libbinio.

**Comment by Malvineous** [comment]
Happy to merge a PR if you're willing to do one for this too!
