### ISSUE TITLE
Best way to make a library for windows

### ISSUE THREAD

**Issue by turric4n** [adplug/adplug#7]
Hi, 

I need a backend Adlib emulator library (under Win32) and this is an awesome library but I cannot compile it. How can I compile this? I follow your manual instructions but fails everytime. 

Also I tried to compile it with Windows CodeBlocks using .h references : 

```c++
#include <iostream>
#include <fstream>
#include <stdio.h>
#include <stdlib.h>
#include <stdarg.h>
#include <conio.h>
#include <adplug.h>
#include <analopl.h>

using namespace std;


int main()
{
    CAdPlug *adplug;
    cout << adplug->get_version();
    return 0;
}
```
but fails : 
```
||=== Build: Debug in ADPlugTest (compiler: GNU GCC Compiler) ===|
obj\Debug\main.o||In function `main':|
E:\CODE\C++\adplugtest\ADPlugTest\main.cpp|16|undefined reference to `CAdPlug::get_version()'|
||=== Build failed: 1 error(s), 0 warning(s) (0 minute(s), 0 second(s)) ===|
```
Help will be apreciated!

Thanks

**Comment by Malvineous** [comment]
It looks like you forgot to link the library, so the compiler can't find the AdPlug functions you are using.  If you Google a bit about how to link in libraries then you should have your answer.

**Comment by turric4n** [comment]
Thnaks for your fast response. :+1:  

I don't have compiled libraries but I have .cpp instead. Can I use .cpp files?

**Comment by Malvineous** [comment]
I'm not sure - I don't think anyone has used AdPlug like that before so you'll have to figure it all out yourself if you do that.  Usually you just compile AdPlug as a separate project to produce a .dll, then add it as a reference to your original project, and the IDE takes care of it.  If you are using CodeBlocks, it might be worth looking at their docs or asking on their forum, as I've not used it before so I don't know how to compile and link to libraries with it.

**Comment by turric4n** [comment]
Thanks Malvineous, What is the best compiler to make an Adplug .DLL? Do you know if somebody has compiled Adplug as DLL?

**Comment by Malvineous** [comment]
I'm not sure - these days I do everything under Linux.  I'm sure Google will help!  I'm going to mark this issue as closed now because it's not really related to AdPlug specifically, it's more a question about how to compile and link libraries in general.
