### ISSUE TITLE
Wrong AdPlug NuGet package version 2.3.1271

### ISSUE THREAD

**Issue by binarymaster** [adplug/adplug#80]
Currently Winamp plugin builder obtains the latest AdPlug package from NuGet thanks to @Corak667's commit https://github.com/adplug/winamp/commit/b7ed1fc2359353f7571b377a8c2648883145b734.

However there's a problem with @SoapGentoo's release commit https://github.com/adplug/adplug/commit/efe452df461d51dc741fbe063b8bf357dc7d0f10:
```diff
-version: 2.3-beta{build}
+version: 2.3.1{build}
```

In the release commit `{build}` postfix should not be used. So now we have a NuGet package with wrong version 2.3.1271 and AppVeyor builder fetches it as a latest build instead of recent betas.

From https://ci.appveyor.com/project/AdPlug/winamp/build/1.9-beta59 :
```
Retrieving package 'adplug 2.3.1271' from 'nuget.org'.
```
This issue blocks https://github.com/adplug/winamp/issues/18

Any ideas how to solve this problem? Maybe it's possible to remove incorrect package from NuGet and then create a separate branch with correct release version number? :thinking:

**Comment by Malvineous** [comment]
I've hidden those packages on NuGet so if that works can you push the necessary changes to fix the issue?

**Comment by binarymaster** [comment]
Seems ok, let's retest Winamp plugin build...

From https://ci.appveyor.com/project/AdPlug/adplug/builds/22606128 :
```
 >Attempting to build package from 'adplug.nuspec'.
 >Successfully created package 'C:\projects\adplug\adplug.2.3.1.nupkg'.
 >WARNING: NU5125: The 'licenseUrl' element will be deprecated. Consider using the 'license' element instead.
 >Attempting to build package from 'adplug.symbols.nuspec'.
 >Successfully created package 'C:\projects\adplug\adplug.symbols.2.3.1.nupkg'.
 >WARNING: NU5125: The 'licenseUrl' element will be deprecated. Consider using the 'license' element instead.
Uploading artifact adplug.2.3.1.nupkg (68,477,559 bytes)...100%
Uploading artifact adplug.symbols.2.3.1.nupkg (650,890 bytes)...100%
Deploying using NuGet provider
Publishing adplug.2.3.1.nupkg to https://www.nuget.org/api/v2/package...OK
Publishing adplug.symbols.2.3.1.nupkg to https://www.nuget.org/api/v2/package...OK
Total packages published: 2
Build success
```

**Comment by binarymaster** [comment]
Yes now everything works ok, but Winamp plugin needs an update after recent changes to the core. :slightly_smiling_face:
